### ISSUE TITLE
Step no. 2 : sbt clean assembly issue 

### ISSUE THREAD

**Issue by ramkumar1308** [PagerDuty/gocd-hipchat-plugin#8]
Hi ,

i am getting below error when i am executing sbt clean assembly command . Please help !

```
$ sbt clean assembly
[info] Set current project to sbt (in build file:/C:/Program%20Files%20(x86)/sb
/)
java.lang.RuntimeException: Could not create directory C:\Program Files (x86)\s
t\target\streams\$global\projectDescriptors\$global\streams
        at scala.sys.package$.error(package.scala:27)
        at sbt.IO$.createDirectory(IO.scala:166)
        at sbt.IO$.touch(IO.scala:142)
        at sbt.std.Streams$$anon$3$$anon$2.make(Streams.scala:129)
        at sbt.std.Streams$$anon$3$$anon$2.text(Streams.scala:113)
        at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:124)
        at sbt.std.TaskStreams$class.log(Streams.scala:56)
        at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:102)
        at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:102)
        at sbt.EvaluateTask$$anonfun$logIncomplete$2.log$1(EvaluateTask.scala:2
9)
        at sbt.EvaluateTask$$anonfun$logIncomplete$2.apply(EvaluateTask.scala:2
3)
        at sbt.EvaluateTask$$anonfun$logIncomplete$2.apply(EvaluateTask.scala:2
8)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply
TraversableLike.scala:772)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.
cala:771)
        at sbt.EvaluateTask$.logIncomplete(EvaluateTask.scala:268)
        at sbt.EvaluateTask$.logIncResult(EvaluateTask.scala:261)
        at sbt.EvaluateTask$.run$1(EvaluateTask.scala:348)
        at sbt.EvaluateTask$.runTask(EvaluateTask.scala:361)
        at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:64)
        at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:62)
        at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:293)
        at sbt.Aggregation$.timedRun(Aggregation.scala:62)
        at sbt.Aggregation$.runTasks(Aggregation.scala:71)
        at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:32)
        at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:31)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.sc
la:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.sc
la:60)
        at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(A
gregation.scala:153)
        at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(A
gregation.scala:152)
        at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$ev
luate$1$1$$anonfun$apply$10.apply(Act.scala:244)
        at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$ev
luate$1$1$$anonfun$apply$10.apply(Act.scala:241)
        at sbt.Command$.process(Command.scala:92)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
[error] Could not create directory C:\Program Files (x86)\sbt\target\streams\$g
obal\projectDescriptors\$global\streams
[error] Use 'last' for the full log.
```

Regards,
Ram

**Comment by ranjib** [comment]
what version of gocd you are running?

**Comment by ramkumar1308** [comment]
Go 15.1

**Comment by ranjib** [comment]
currently we have only tested in on 14.x series. im planning to start testing on 15.x, but it will take some time

**Comment by ramkumar1308** [comment]
oh okay ! thanks for the response ! Recently we have updated our GO to 15.1.

**Comment by esigler** [comment]
My apologies, this software is no longer actively being maintained by PagerDuty. We've switched over to Slack, and can no longer easily develop for this plugin. If you want to take over ownership, please email opensource@pagerduty.com.  Closing this issue.
